# Generated by Django 5.2 on 2026-04-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('age', models.IntegerField(help_text='Âge du patient (18-120 ans)')),
                ('hypertension', models.BooleanField(default=False)),
                ('heart_disease', models.BooleanField(default=False)),
                ('smoking_history', models.CharField(blank=True, max_length=20, null=True)),
                ('bmi', models.FloatField()),
                ('activite_physique', models.CharField(blank=True, choices=[('FAIBLE', 'Faible'), ('MODERE', 'Modéré'), ('ELEVE', 'Élevé')], max_length=10, null=True)),
                ('HbA1c_level', models.FloatField()),
                ('blood_glucose_level', models.IntegerField()),
                ('diabetes', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
