# Generated by Django 5.2 on 2026-04-26 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdata',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='diabetes',
            field=models.BooleanField(default=False),
        ),
    ]
